twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: '%env(SITE_NAME)%'
        site_short: '%env(SITE_SHORT)%'
        appState: '@App\Service\AppState'

when@test:
    twig:
        strict_variables: true
